org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.23
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=pokeloader
mod_name=Pokeloader
mod_license=GNU-AGPL-3.0-only
mod_version=2.0.0-alpha.1+1.20.1-forge
mod_group_io=io.github.littleperson101.pokeloader
mod_authors=LittlePerson101
mod_description=Displays the iconic Pokeball on game startup with some satisfying audio as well.
